post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

use_frameworks!

platform :ios, '13.0'

project 'BPBleOTA.xcodeproj'

target 'BPBleOTA_Example' do
  
  pod 'BPBleOTA', :path => '../'
  
  pod 'MBProgressHUD'
  
  target 'BPBleOTA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
