use_frameworks!

platform :ios, '9.0'

project 'BPBleOTA.xcodeproj'

target 'BPBleOTA_Example' do
  pod 'iOSDFULibrary', '~> 4.13.0'
  pod 'iOSMcuManagerLibrary' ,"~> 1.2.7.0"
  pod 'BPBleOTA', :path => '../'

  target 'BPBleOTA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
