use_frameworks!

platform :ios, '9.0'

project 'BPBleOTA.xcodeproj'

target 'BPBleOTA_Example' do
  
  pod 'BPBleOTA', :path => '../'
  
  pod 'MBProgressHUD'
  
  target 'BPBleOTA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
